### ISSUE TITLE
Steps to use this library in Angular 4

### ISSUE THREAD

**Issue by ratnam99** [meanie/angular-duplicate-requests-filter#1]
Hi!!
I'm having problem in implementing this library in Angular 4 as the Readme is not very descriptive. 
So, please take some time out and respond me the steps to use this library in Angular 4.

Thank You!

**Comment by adamreisnz** [comment]
Sorry, this library is only for Angular 1.6.

**Comment by ratnam99** [comment]
Is there any possibility that you can upgrade it for Angular 4?

**Comment by adamreisnz** [comment]
Sorry, no. I've been rather disillusioned by the direction Angular has been taken in version 2 and 4, in particular about forcing Typescript down people's throats and not offering proper solutions for people wanting to use Angular in plain ES6, as well as the huge amount of discrepancies and instability between different versions and the lacking and inconsistent documentation.

Angular 1 is still enjoying strong support and continued development, so this is where I'm focussed on at the moment with these packages.
